### ISSUE TITLE
Change Puppet module directory structure

### ISSUE THREAD

**Issue by mmoll** [theforeman/foreman-infra#1069]
I want to collect comments from @ehelms @evgeni @ekohl for the following separation:

In the puppet `modules` folder, only modules that are available on puppet forge are kept.

In the new puppet `external_modules` folder, all modules from external git repos (e.g. dirvish) or are kept.

In the new puppet `local_modules` folder, all modules that are files in this repo, are kept.

This way, r10k can be used later for `modules` and `external_modules`, which would unclutter this repo here.

**Comment by ekohl** [comment]
In general I'd be in favor of such a solution. We'd also drop the configs then.

**Comment by ehelms** [comment]
I would generally also be in favor of this. When I first started reading this I thought maybe it would be an organization our concerns (e.g. jenkins related modules together). Any way to also achieve that?

**Comment by mmoll** [comment]
@ehelms I'm a bit unsure how this structure would look like and what problem it would solve...

When talking about jenkins, that would be a `jenkins_modules` folder, containing at least the modules that start with "jenkins", correct?

**Comment by ehelms** [comment]
I think our repository layout tries to solve two problems:

 1) providing a puppet structure that can be imported and used by a Puppet server
 2) provide a place to make changes and store them in git

For newcomers and the casual developer, #2 can be hard to understand how all the pieces fit together and where certain parts live because its a big bucket of modules. Your example of Jenkins is a good one. There are a few obvious ones: 

 * jenkins_master
 * jenkins
 * jenkins_job_builder

But also `slave` is part of this sub-set of infrastructure. Similarly, I imagine there are modules related to the the web hosts for yum/deb, our application infrastructure (prprocessor, rbot). Something like `rvm` I know is used by Jenkins, but maybe its used by more than that?

We don't have to solve this problem with your proposal. I did think it worthy of at least discussing in case there was any obvious quick wins here to help with #2.

**Comment by mmoll** [comment]
@ehelms Ah, I see... Unfortunately I don't see any quick wins, but as I would want all that to happen in small steps, maybe we can throw something in later.

At the end of the day, the easiest would be to merge all modules together into one dir in the deployment job anyway, so there are a lot of possibilities...

**Comment by ekohl** [comment]
One way to solve that is to think more in modules/profiles(/roles). https://puppet.com/docs/pe/2017.2/r_n_p_full_example.html has the full story, but the short version is that we'd have modules (`jenkins`) and a profile module. This would mean a class `profile::jenkins::master` and another class `profile::jenkins::slave`. With Foreman as an ENC I don't see a lot of benefit for roles since we can assign profiles to hostgroups and compose in that way. In the end we'd only include the `profile` module into foreman and nothing else.
