### ISSUE TITLE
Automation of packaging bumping plugins

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#1693]
See https://github.com/theforeman/foreman-packaging/pull/7369 for details

**Comment by ehelms** [comment]
Infrastructure SIG notes:

- Need a special account for creating the branches to open the PRs
- We can use the existing [theforeman-bot](https://github.com/theforeman-bot/foreman-packaging) or auto-delete of branches when PR is merged

**Comment by ekohl** [comment]
As noted during the Infra SIG (https://community.theforeman.org/t/infrastructure-sig-meeting-notes-2022-01-14/26860#automation-of-package-bumping-plugins-and-dependencieshttpsgithubcomtheforemanforeman-infraissues1693-7), the work has now been merged. It still needs to run and there's no schedule yet, but we're close.

**Comment by evgeni** [comment]
- did run
- Jenkins doesn't recognize the author and thus doesn't run CI, which is bad -- probably there is a list somewhere where we can add the actions user to
- foreman-deface (in deb/plugins) is not really a plugin, but was identified as such and we can just bump it with the same process
- idea: shall we do bumping (but on .z versions) in stable branches? [scope creep, but an idea]
  - not all plugins really follow semver
  - ideally stable branches only have cherrypicks, in reality multiple plugin branches exist and are supported
  - instead of automatical "all the changes", enhance workflow with inputs for plugin and branch, and thus allow users to say "now bump only ansible in 3.1"
- look into https://github.com/theforeman/foreman-packaging/runs/4840210800?check_suite_focus=true

definition of done: this runs on a schedule

**Comment by evgeni** [comment]
- semver issues fixed by ewoud
- jenkins should accept builds automatically after https://github.com/theforeman/jenkins-jobs/pull/192 and https://github.com/theforeman/jenkins-jobs/pull/193
- deface merged

- there is an "issue" with empty runs: https://github.com/theforeman/foreman-packaging/actions/runs/1969114770 "
Error when evaluating 'strategy' for job 'bump_rpm'. .github/workflows/bump_packages.yml (Line: 30, Col: 9): Matrix must define at least one vector"

**Comment by ehelms** [comment]
> * there is an "issue" with empty runs: https://github.com/theforeman/foreman-packaging/actions/runs/1969114770 "
>   Error when evaluating 'strategy' for job 'bump_rpm'. .github/workflows/bump_packages.yml (Line: 30, Col: 9): Matrix must define at least one vector"

What causes an empty run?

**Comment by evgeni** [comment]
> > * there is an "issue" with empty runs: https://github.com/theforeman/foreman-packaging/actions/runs/1969114770 "
> >   Error when evaluating 'strategy' for job 'bump_rpm'. .github/workflows/bump_packages.yml (Line: 30, Col: 9): Matrix must define at least one vector"
> 
> What causes an empty run?

When there is nothing to update, the "find updates" stage returns an empty list, and then the create PRs stage freaks out as the matrix definition is invalid.

**Comment by ekohl** [comment]
I've played around with this, but I haven't really found a good way. The only thing I didn't try yet is to add something like `if: ${{ matrix.vector != [] }}`.

**Comment by evgeni** [comment]
- enable cronjob
- see if we can make it ping discourse somehow?

**Comment by evgeni** [comment]
- skipping empty runs was implemented in https://github.com/theforeman/foreman-packaging/pull/7993 (you can't compare to an empty list `[]` but to a string of an empty list `'[]'` before you call `fromJson` :roll_eyes: 
- email is being worked on in https://github.com/theforeman/foreman-packaging/pull/7983

**Comment by evgeni** [comment]
and the crobjob enablement is in https://github.com/theforeman/foreman-packaging/pull/8064 -- that will be the last tick on this list

**Comment by evgeni** [comment]
AI: check if notifications really works, and close if does (or fix!)

**Comment by ehelms** [comment]
Notifications are currently:

 * Per package (we should look to instead do this for the whole job?)
 * There is an SSL error sending the email:

```
Error: 140431905449856:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

**Comment by evgeni** [comment]
Can we set `secure: false` here? https://github.com/theforeman/foreman-packaging/blob/master/.github/workflows/bump_packages.yml#L125

Or just unset it, if I read the docs of the action right, it should only try TLS on port 465 by default.

**Comment by ehelms** [comment]
Let's give that a try https://github.com/theforeman/foreman-packaging/pull/8235

**Comment by evgeni** [comment]
```
Error: Can't send mail - all recipients were rejected: 450 4.7.1 <ci@community.theforeman.org>: Recipient address rejected: Internal error, API request failed
```

progress?

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/8244

**Comment by evgeni** [comment]
Well, it does send a mail now…

https://community.theforeman.org/t/foreman-packaging-update-rpm-packages-github-action-failed/29453/2

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/8245
