### ISSUE TITLE
Switch katello-host-tools testing to Alma

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#2090]

**Comment by ekohl** [comment]
We have CI list a few Dockerfiles here: https://github.com/Katello/katello-host-tools/blob/37c7fdfe0b9fdfb794174415098d45b46aac3c71/.github/workflows/pull_request.yml#L25-L32

For this one we need to at least update EL8. This line needs to be changed:

https://github.com/Katello/katello-host-tools/blob/37c7fdfe0b9fdfb794174415098d45b46aac3c71/images/Dockerfile.el8#L1

You can try to see if ubi8 works, but otherwise it can be changed to AlmaLinux 8.

Unrelated to this change, but I just noticed that `python3-tracer` is installed, but it's no longer a dependency:
https://github.com/Katello/katello-host-tools/blob/37c7fdfe0b9fdfb794174415098d45b46aac3c71/images/Dockerfile.el8#L4C55-L4C69
That can be dropped as well.

**Comment by archanaserver** [comment]
https://github.com/Katello/katello-host-tools/pull/157
https://github.com/Katello/katello-host-tools/pull/158

**Comment by ekohl** [comment]
https://github.com/Katello/katello-host-tools/pull/157 was merged, so closing this.
