### ISSUE TITLE
Set up remote execution plugin

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-infra#469]
Blocked By: GH-468

**Comment by ekohl** [comment]
This is now done. Foreman and the proxy are configured. The ssh_user class is added to the builders host group so it should that up. I've configured it to connect by IP since our DNS is a mess, except for tfmslave01.timogoebel.net where DNS is correct but IP isn't. Then there are a few where there is no correct administration in Foreman so they're unreachable.
